#!/usr/bin/env sh

# Change to the desired directory
cd /mnt/Localdisk/folder/wall/ || exit

# Get a list of all files in the directory
files=(*)

# Pick a random index
random_index=$((RANDOM % ${#files[@]}))

# Pick the random file
random_file=${files[random_index]}

# Determine whether to pick the file above or below
direction=$((RANDOM % 2))  # 0 for above, 1 for below

# Calculate the index of the file above or below
if [ "$direction" -eq 0 ]; then
    target_index=$((random_index - 1))
else
    target_index=$((random_index + 1))
fi

# Ensure the target index is within bounds
if [ "$target_index" -ge 0 ] && [ "$target_index" -lt "${#files[@]}" ]; then
    target_file=${files[target_index]}

    # Run pywal to generate color scheme and set the wallpaper
    wal -i "$random_file"
    
    # Get colors from the cache file generated by pywal
    cache_file_path=~/.cache/wal/colors
    colors=($(cat "$cache_file_path"))



    # Define the CSS file path
    css_file_path=~/.config/waybar/color-waybar.css
    # Customize the CSS file with the extracted colors
    echo "@define-color foreground ${colors[0]};" > "$css_file_path"
    echo "@define-color background ${colors[1]};" >> "$css_file_path"
    echo "@define-color cursor ${colors[2]};" >> "$css_file_path"
    echo "@define-color color0 ${colors[3]};" >> "$css_file_path"
    # Add your additional colors here, customize as needed
    echo "@define-color color1 ${colors[4]};" >> "$css_file_path"
    echo "@define-color color2 ${colors[5]};" >> "$css_file_path"
    echo "@define-color color3 ${colors[6]};" >> "$css_file_path"
    echo "@define-color color4 ${colors[7]};" >> "$css_file_path"
    echo "@define-color color5 ${colors[8]};" >> "$css_file_path"

    # ... Add more colors as desired

    swww img "$random_file" --transition-type wipe --transition-angle 10 --transition-step 90 --transition-fps 90

    # Output the selected file above or below
    # notify-send "Selected file: $target_file"
    
    # Send SIGUSR1 to each waybar process
    for pid in $(pgrep -x "waybar"); do
        kill -SIGUSR2 "$pid"
    done
    
else
    notify-send "Not enough files or invalid index for the selected direction."
fi
